"""Base strategy interface for all trading strategies.

Every strategy implements the same interface so the backtest engine
and bot can run them uniformly.
"""
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

import pandas as pd


class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"


class Regime(str, Enum):
    MEAN_REVERT = "MEAN_REVERT"
    TRENDING = "TRENDING"
    RANDOM = "RANDOM"
    TRANSITION = "TRANSITION"
    CHAOTIC = "CHAOTIC"


@dataclass
class Signal:
    """A trading signal generated by a strategy."""

    timestamp: pd.Timestamp
    symbol: str
    direction: Direction
    price: float
    confidence: float = 1.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    strategy_id: str = ""
    metadata: dict = field(default_factory=dict)

    @property
    def is_long(self) -> bool:
        return self.direction == Direction.LONG

    @property
    def is_short(self) -> bool:
        return self.direction == Direction.SHORT


@dataclass
class StrategyConfig:
    """Base configuration for all strategies."""

    risk_per_trade: float = 0.01  # 1% of portfolio
    max_positions: int = 5
    strategy_id: str = ""


class BaseStrategy:
    """Abstract base class for all strategies."""

    def __init__(self, config: StrategyConfig):
        self.config = config
        self.positions: dict[str, Signal] = {}  # symbol -> active signal

    @property
    def name(self) -> str:
        return self.config.strategy_id or self.__class__.__name__

    def generate_signals(self, data: dict[str, pd.DataFrame]) -> list[Signal]:
        """Generate trading signals from market data.

        Args:
            data: Dict mapping symbol to OHLCV DataFrame.

        Returns:
            List of Signal objects.
        """
        raise NotImplementedError

    def get_regime_filter(self, returns: pd.DataFrame) -> dict[str, Regime]:
        """Get regime classification for each symbol (optional override).

        Args:
            returns: DataFrame of returns (columns = symbols).

        Returns:
            Dict mapping symbol to Regime.
        """
        return {}

    def on_fill(self, signal: Signal, fill_price: float) -> None:
        """Called when a signal is filled (position opened)."""
        self.positions[signal.symbol] = signal

    def on_close(self, symbol: str) -> None:
        """Called when a position is closed."""
        self.positions.pop(symbol, None)

    def can_open(self, symbol: str) -> bool:
        """Check if a new position can be opened for this symbol."""
        if symbol in self.positions:
            return False
        return len(self.positions) < self.config.max_positions
